variables:
  DOCKER_DRIVER: overlay2

stages:
  - maven-build
  - docker-build

maven-build:
  image: maven:3.6.1-jdk-8-alpine
  stage: maven-build
  script:
    - mvn clean
    - mvn package
  artifacts:
    name: hsm-util
    paths:
      - target/*.jar
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: push
    paths:
      - target/*.jar
  only:
    - master

docker-build:
  image: docker:latest
  stage: docker-build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - IMAGE=hsm-util:latest
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE/$IMAGE"
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
  only:
    - master
